//! Float text — written from ALS-T13 (shortest round-tripping decimal,
//! Dragon4/Ryū-equivalent), ALS-T9 (`to_fixed`: round-half-to-even on the
//! EXACT binary value), ALS-E3/R2/R4 (display forms, `-0.0` sign, named
//! non-finite constants). Everything here is exact big-integer arithmetic —
//! no host formatting, no host parsing (ADR-0015 clause 5): the digits are
//! generated by the classic Steele–White / Dragon4 free-format algorithm.

use crate::value::F64;

/// Minimal unsigned big integer (little-endian u32 limbs). Only what the
/// digit generators need: compare, add, subtract, small-multiply, shift.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Big(Vec<u32>);

impl Big {
    pub fn from_u64(v: u64) -> Big {
        let mut b = Big(vec![v as u32, (v >> 32) as u32]);
        b.norm();
        b
    }
    fn norm(&mut self) {
        while self.0.len() > 1 && *self.0.last().unwrap() == 0 {
            self.0.pop();
        }
    }
    pub fn is_zero(&self) -> bool {
        self.0.iter().all(|&l| l == 0)
    }
    pub fn cmp(&self, other: &Big) -> std::cmp::Ordering {
        if self.0.len() != other.0.len() {
            return self.0.len().cmp(&other.0.len());
        }
        for i in (0..self.0.len()).rev() {
            if self.0[i] != other.0[i] {
                return self.0[i].cmp(&other.0[i]);
            }
        }
        std::cmp::Ordering::Equal
    }
    pub fn add(&self, other: &Big) -> Big {
        let n = self.0.len().max(other.0.len());
        let mut out = Vec::with_capacity(n + 1);
        let mut carry = 0u64;
        for i in 0..n {
            let a = *self.0.get(i).unwrap_or(&0) as u64;
            let b = *other.0.get(i).unwrap_or(&0) as u64;
            let s = a + b + carry;
            out.push(s as u32);
            carry = s >> 32;
        }
        if carry > 0 {
            out.push(carry as u32);
        }
        let mut b = Big(out);
        b.norm();
        b
    }
    /// self - other; caller guarantees self >= other
    pub fn sub(&self, other: &Big) -> Big {
        let mut out = Vec::with_capacity(self.0.len());
        let mut borrow = 0i64;
        for i in 0..self.0.len() {
            let a = self.0[i] as i64;
            let b = *other.0.get(i).unwrap_or(&0) as i64;
            let mut d = a - b - borrow;
            if d < 0 {
                d += 1 << 32;
                borrow = 1;
            } else {
                borrow = 0;
            }
            out.push(d as u32);
        }
        debug_assert_eq!(borrow, 0, "Big::sub underflow");
        let mut b = Big(out);
        b.norm();
        b
    }
    pub fn mul_small(&self, m: u32) -> Big {
        let mut out = Vec::with_capacity(self.0.len() + 1);
        let mut carry = 0u64;
        for &l in &self.0 {
            let p = l as u64 * m as u64 + carry;
            out.push(p as u32);
            carry = p >> 32;
        }
        while carry > 0 {
            out.push(carry as u32);
            carry >>= 32;
        }
        let mut b = Big(out);
        b.norm();
        b
    }
    pub fn shl(&self, bits: u32) -> Big {
        let limbs = (bits / 32) as usize;
        let rem = bits % 32;
        let mut out = vec![0u32; limbs];
        if rem == 0 {
            out.extend_from_slice(&self.0);
        } else {
            let mut carry = 0u32;
            for &l in &self.0 {
                out.push((l << rem) | carry);
                carry = l >> (32 - rem);
            }
            if carry > 0 {
                out.push(carry);
            }
        }
        let mut b = Big(out);
        b.norm();
        b
    }
    pub fn mul_pow10(&self, mut n: u32) -> Big {
        let mut b = self.clone();
        while n >= 9 {
            b = b.mul_small(1_000_000_000);
            n -= 9;
        }
        while n > 0 {
            b = b.mul_small(10);
            n -= 1;
        }
        b
    }
}

/// (mantissa, exponent) with value = m * 2^e, m the FULL significand
/// (implicit bit included for normals). None for zero / non-finite.
fn decompose(x: f64) -> Option<(u64, i32)> {
    if x == 0.0 || !x.is_finite() {
        return None;
    }
    let bits = x.abs().to_bits();
    let raw_exp = (bits >> 52) as i32;
    let frac = bits & ((1u64 << 52) - 1);
    if raw_exp == 0 {
        Some((frac, -1074)) // subnormal (ALS-T21: preserved)
    } else {
        Some((frac | (1u64 << 52), raw_exp - 1075))
    }
}

/// Shortest round-tripping digits (ALS-T13): returns (digits, k) with the
/// value ≈ 0.d1d2… × 10^k. Free-format Dragon4 (Steele & White FPP2 with
/// even-mantissa closed bounds — ties-to-even round-trip).
pub fn shortest_digits(x: f64) -> (Vec<u8>, i32) {
    let (m, e) = decompose(x).expect("finite non-zero");
    // scaled value R/S, boundaries M+ / M-
    let (mut r, mut s, mut m_plus, mut m_minus);
    if e >= 0 {
        let be = Big::from_u64(1).shl(e as u32);
        r = Big::from_u64(m).shl((e + 1) as u32);
        s = Big::from_u64(2);
        m_plus = be.clone();
        m_minus = be;
    } else {
        r = Big::from_u64(m).shl(1);
        s = Big::from_u64(1).shl((1 - e) as u32);
        m_plus = Big::from_u64(1);
        m_minus = Big::from_u64(1);
    }
    // the lower gap is halved when m is the smallest normal significand
    if m == (1u64 << 52) && e > -1074 {
        r = r.shl(1);
        s = s.shl(1);
        m_plus = m_plus.shl(1);
    }
    // an EVEN significand owns its boundaries (ties round back to it)
    let inclusive = m % 2 == 0;
    let within_low = |a: &Big, b: &Big| {
        if inclusive {
            a.cmp(b) != std::cmp::Ordering::Greater
        } else {
            a.cmp(b) == std::cmp::Ordering::Less
        }
    };
    // estimate k = ceil(log10(x)) and fix up
    let mut k: i32 = {
        let est = (x.abs().log10()).ceil();
        est as i32
    };
    if k >= 0 {
        s = s.mul_pow10(k as u32);
    } else {
        let scale = Big::from_u64(1).mul_pow10((-k) as u32);
        r = r.mul_small(1); // keep shape
        r = mul_big(&r, &scale);
        m_plus = mul_big(&m_plus, &scale);
        m_minus = mul_big(&m_minus, &scale);
    }
    // fixup: ensure r + m_plus <=(/<) s  fails → k was low
    loop {
        let hi = r.add(&m_plus);
        let over = if inclusive {
            hi.cmp(&s) == std::cmp::Ordering::Greater
        } else {
            hi.cmp(&s) != std::cmp::Ordering::Less
        };
        if over {
            s = s.mul_small(10);
            k += 1;
        } else {
            break;
        }
    }
    // also ensure the first digit is non-zero: (r + m_plus) * 10 > s
    loop {
        let hi = r.add(&m_plus).mul_small(10);
        let under = if inclusive {
            hi.cmp(&s) == std::cmp::Ordering::Less
        } else {
            hi.cmp(&s) != std::cmp::Ordering::Greater
        };
        if under {
            r = r.mul_small(10);
            m_plus = m_plus.mul_small(10);
            m_minus = m_minus.mul_small(10);
            k -= 1;
        } else {
            break;
        }
    }
    let mut digits = Vec::new();
    loop {
        r = r.mul_small(10);
        m_plus = m_plus.mul_small(10);
        m_minus = m_minus.mul_small(10);
        // digit = floor(r / s) by repeated subtraction (digit <= 9)
        let mut d = 0u8;
        while r.cmp(&s) != std::cmp::Ordering::Less {
            r = r.sub(&s);
            d += 1;
        }
        let low = within_low(&r, &m_minus);
        let high = {
            let sum = r.add(&m_plus);
            if inclusive {
                sum.cmp(&s) != std::cmp::Ordering::Less
            } else {
                sum.cmp(&s) == std::cmp::Ordering::Greater
            }
        };
        match (low, high) {
            (false, false) => digits.push(d),
            (true, false) => {
                digits.push(d);
                break;
            }
            (false, true) => {
                digits.push(d + 1);
                break;
            }
            (true, true) => {
                // closest boundary decides; tie → even-ish: round up when 2r >= s
                let two_r = r.shl(1);
                let up = match two_r.cmp(&s) {
                    std::cmp::Ordering::Greater => true,
                    std::cmp::Ordering::Less => false,
                    std::cmp::Ordering::Equal => d % 2 == 1,
                };
                digits.push(if up { d + 1 } else { d });
                break;
            }
        }
    }
    (digits, k)
}

fn mul_big(a: &Big, b: &Big) -> Big {
    // schoolbook; sizes here are tiny (≤ ~40 limbs)
    let mut out = Big::from_u64(0);
    let mut shifted = a.clone();
    for (i, &limb) in b.0.iter().enumerate() {
        if limb != 0 {
            let mut part = shifted.mul_small(limb);
            let _ = i;
            out = out.add(&part);
            part.norm();
        }
        shifted = shifted.shl(32);
    }
    out
}

/// Positional rendering of (digits, k): "0.d…" forms for k <= 0, plain
/// integer-with-fraction otherwise. NEVER exponent notation — the native
/// target's Display prints full positional digits and ALS-T13's canonical
/// form follows it.
fn positional(digits: &[u8], k: i32, force_point: bool) -> String {
    let mut out = String::new();
    if k <= 0 {
        out.push_str("0.");
        for _ in 0..(-k) {
            out.push('0');
        }
        for &d in digits {
            out.push((b'0' + d) as char);
        }
    } else if (k as usize) >= digits.len() {
        for &d in digits {
            out.push((b'0' + d) as char);
        }
        for _ in 0..(k as usize - digits.len()) {
            out.push('0');
        }
        if force_point {
            out.push_str(".0");
        }
    } else {
        for (i, &d) in digits.iter().enumerate() {
            if i == k as usize {
                out.push('.');
            }
            out.push((b'0' + d) as char);
        }
    }
    out
}

/// `float.to_string` (ALS-T13 / ALS-E3): shortest round trip, keeps `.0` on
/// integral values, keeps the sign of `-0.0`; inf / -inf / NaN as names
/// (ALS-R4).
pub fn to_string_form(f: F64) -> String {
    let x = f.0;
    if x.is_nan() {
        return "NaN".into();
    }
    if x.is_infinite() {
        return if x > 0.0 { "inf".into() } else { "-inf".into() };
    }
    if x == 0.0 {
        return if x.is_sign_negative() {
            "-0.0".into()
        } else {
            "0.0".into()
        };
    }
    let (digits, k) = shortest_digits(x);
    let body = positional(&digits, k, true);
    if x < 0.0 {
        format!("-{body}")
    } else {
        body
    }
}

/// Interpolation / container Display (ALS-R2): same digits, but an integral
/// value drops the `.0` (`10.0` → `10`, `-0.0` → `-0`).
pub fn display_form(f: F64) -> String {
    let x = f.0;
    if x.is_nan() {
        return "NaN".into();
    }
    if x.is_infinite() {
        return if x > 0.0 { "inf".into() } else { "-inf".into() };
    }
    if x == 0.0 {
        return if x.is_sign_negative() {
            "-0".into()
        } else {
            "0".into()
        };
    }
    let (digits, k) = shortest_digits(x);
    let body = positional(&digits, k, false);
    if x < 0.0 {
        format!("-{body}")
    } else {
        body
    }
}

/// `float.to_fixed(x, n)` (ALS-T9): round-half-to-even on the EXACT binary
/// value — the decimal expansion of m·2^e is finite; we compare the true
/// remainder against one half of the last kept unit, exactly.
pub fn to_fixed(f: F64, n: i64) -> Option<String> {
    let x = f.0;
    if !x.is_finite() || !(0..=1074).contains(&n) {
        return None;
    }
    let neg = x.is_sign_negative();
    let (m, e) = match decompose(x) {
        None => {
            // ±0
            let mut s = String::from("0");
            if n > 0 {
                s.push('.');
                for _ in 0..n {
                    s.push('0');
                }
            }
            return Some(if neg { format!("-{s}") } else { s });
        }
        Some(t) => t,
    };
    // value = m * 2^e; scaled = value * 10^n = num / den, den a power of two
    let num0 = Big::from_u64(m).mul_pow10(n as u32);
    let (num, den) = if e >= 0 {
        (num0.shl(e as u32), Big::from_u64(1))
    } else {
        (num0, Big::from_u64(1).shl((-e) as u32))
    };
    // integer quotient and remainder of num / den (long division by shifts)
    let (q, r) = big_divmod(&num, &den);
    // round half to even on the exact remainder
    let twice = r.shl(1);
    let round_up = match twice.cmp(&den) {
        std::cmp::Ordering::Greater => true,
        std::cmp::Ordering::Less => false,
        std::cmp::Ordering::Equal => is_odd(&q),
    };
    let q = if round_up {
        q.add(&Big::from_u64(1))
    } else {
        q
    };
    // q is the value scaled by 10^n; render with a decimal point n from the right
    let mut ds = decimal_digits(&q);
    while (ds.len() as i64) <= n {
        ds.insert(0, 0);
    }
    let point = ds.len() as i64 - n;
    let mut out = String::new();
    for (i, d) in ds.iter().enumerate() {
        if i as i64 == point && n > 0 {
            out.push('.');
        }
        out.push((b'0' + d) as char);
    }
    Some(if neg { format!("-{out}") } else { out })
}

fn is_odd(b: &Big) -> bool {
    b.0.first().map(|l| l & 1 == 1).unwrap_or(false)
}

fn big_divmod(num: &Big, den: &Big) -> (Big, Big) {
    if den == &Big::from_u64(1) {
        return (num.clone(), Big::from_u64(0));
    }
    // binary long division: den is a power of two here, but stay general
    let mut q = Big(vec![0]);
    let mut r = Big::from_u64(0);
    let bits: Vec<bool> = {
        let mut v = Vec::new();
        for &l in num.0.iter() {
            for i in 0..32 {
                v.push((l >> i) & 1 == 1);
            }
        }
        v
    };
    for i in (0..bits.len()).rev() {
        r = r.shl(1);
        if bits[i] {
            r = r.add(&Big::from_u64(1));
        }
        q = q.shl(1);
        if r.cmp(den) != std::cmp::Ordering::Less {
            r = r.sub(den);
            q = q.add(&Big::from_u64(1));
        }
    }
    q.norm();
    r.norm();
    (q, r)
}

fn decimal_digits(b: &Big) -> Vec<u8> {
    // repeated division by 10^9 via u64 chunks
    let mut limbs: Vec<u32> = b.0.clone();
    let mut out: Vec<u8> = Vec::new();
    loop {
        // divide limbs (little endian) by 10, collecting remainder
        let mut rem: u64 = 0;
        let mut all_zero = true;
        for l in limbs.iter_mut().rev() {
            let cur = (rem << 32) | *l as u64;
            *l = (cur / 10) as u32;
            rem = cur % 10;
            if *l != 0 {
                all_zero = false;
            }
        }
        out.push(rem as u8);
        if all_zero {
            break;
        }
    }
    out.reverse();
    out
}

// ── correctly rounded decimal → binary64 (ALS-T2) ───────────────────────

impl Big {
    pub fn from_digits(ds: &str) -> Big {
        let mut b = Big::from_u64(0);
        for c in ds.chars() {
            b = b.mul_small(10).add(&Big::from_u64((c as u8 - b'0') as u64));
        }
        b
    }
    pub fn bit_len(&self) -> i64 {
        for i in (0..self.0.len()).rev() {
            if self.0[i] != 0 {
                return i as i64 * 32 + (32 - self.0[i].leading_zeros() as i64);
            }
        }
        0
    }
    fn to_u64(&self) -> u64 {
        let lo = *self.0.first().unwrap_or(&0) as u64;
        let hi = *self.0.get(1).unwrap_or(&0) as u64;
        (hi << 32) | lo
    }
}

/// The exact nearest binary64 for `digits × 10^scale` (round to nearest,
/// ties to even; ALS-T2: exact for ANY digit count and exponent, denormals
/// and overflow included). Pure big-integer arithmetic.
pub fn parse_decimal(digits: &str, scale: i64) -> f64 {
    let ds = digits.trim_start_matches('0');
    if ds.is_empty() {
        return 0.0;
    }
    // cheap overflow/underflow guards on the decimal magnitude
    let dec_mag = ds.len() as i64 + scale; // number of integer digits, roughly 10^(dec_mag)
    if dec_mag > 310 {
        return f64::INFINITY;
    }
    if dec_mag < -350 {
        return 0.0;
    }
    let d = Big::from_digits(ds);
    let (num0, den0) = if scale >= 0 {
        (d.mul_pow10(scale as u32), Big::from_u64(1))
    } else {
        (d, Big::from_u64(1).mul_pow10((-scale) as u32))
    };
    // find e with q = round(num/den / 2^e), 2^52 <= q < 2^53 (or subnormal)
    let mut e: i64 = num0.bit_len() - den0.bit_len() - 53;
    loop {
        if e < -1074 {
            e = -1074;
        }
        let (num, den) = if e >= 0 {
            (num0.clone(), den0.shl(e as u32))
        } else {
            (num0.shl((-e) as u32), den0.clone())
        };
        let (q, r) = big_divmod(&num, &den);
        let qb = q.bit_len();
        if qb > 53 && e < 972 {
            e += (qb - 53).max(1);
            continue;
        }
        if qb < 53 && e > -1074 {
            e -= (53 - qb).max(1);
            continue;
        }
        // round on the exact remainder
        let twice = r.shl(1);
        let mut qv = q.to_u64();
        let up = match twice.cmp(&den) {
            std::cmp::Ordering::Greater => true,
            std::cmp::Ordering::Less => false,
            std::cmp::Ordering::Equal => qv & 1 == 1,
        };
        if up {
            qv += 1;
            if qv == (1u64 << 53) {
                qv >>= 1;
                e += 1;
            }
        }
        // assemble bits
        if qv == 0 {
            return 0.0;
        }
        let (mant, biased): (u64, i64) = if qv >= (1u64 << 52) {
            (qv - (1u64 << 52), e + 1075)
        } else {
            // subnormal (e == -1074)
            (qv, 0)
        };
        if biased >= 2047 {
            return f64::INFINITY;
        }
        if biased < 0 {
            // should not happen (subnormal path uses biased 0)
            return 0.0;
        }
        return f64::from_bits(((biased as u64) << 52) | mant);
    }
}
