#!/usr/bin/env python3
"""REF-TOTALITY GATE — totality-or-abstain (ADR-0015 clause 2) and the abstain
ledger (decision 5), measured over the judged corpora.

    scripts/check-ref-totality.py [--ref <als-ref>] [--no-build] [--write]

Runs `als-ref run --json` over spec/wasm_cross/*.almd and spec/programs/*.almd
and demands:

  1. NO evaluator fault (`{"error": …}`) on any program — a fault is an
     evaluator bug, never a verdict; an unimplemented form must be an abstain
     with a class (the syntactic half of totality is the compiler's
     exhaustive `match`; this is the run-time half).
  2. Every stdlib `module.fn` the corpora CALL is either implemented
     (`als-ref stdlib-index`) or appears as an abstain class in
     proofs/ref-abstain.toml — nothing silently unknown.
  3. The abstain ledger is honest and shrink-only: the measured count per
     class and the total equal the committed ledger exactly (`--write`
     regenerates it), and the total may only go DOWN across commits — the
     ledger's `ceiling` is the previous total; a higher measured total is
     red (a regression in coverage), a lower one must be ratcheted by the
     same change (four-direction law).

Exit 0 = all hold; 1 = a violation; 2 = environment.
"""
import collections, glob, json, os, re, subprocess, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LEDGER = os.path.join(ROOT, "proofs", "ref-abstain.toml")
CORPORA = ["spec/wasm_cross/*.almd", "spec/programs/*.almd"]
CALL_RE = re.compile(r'\b([a-z][a-z0-9_]*)\.([a-z_][a-z0-9_]*)\s*\(')
MODULES = {
    "string", "list", "map", "set", "int", "float", "value", "result", "option", "math", "datetime", "error", "bytes",
    "matrix", "prim", "int8", "int16", "int32", "uint8", "uint16", "uint32", "uint64", "float32", "json", "fs", "http",
    "env", "io", "random", "regex", "process", "testing", "path", "args", "net", "zlib", "base64", "hex", "html", "mem",
    "fan", "compute", "duration", "i8", "i16", "i32", "u8", "u16", "u32", "u64", "i64", "bool", "char", "tuple", "time",
    "url", "log", "hash", "base", "uuid", "csv", "toml", "yaml",
}


def build(ref_arg):
    if ref_arg:
        return ref_arg
    r = subprocess.run(["cargo", "build", "--release", "--quiet"], cwd=os.path.join(ROOT, "ref"))
    if r.returncode != 0:
        print("::error::ref crate does not build"); sys.exit(1)
    return os.path.join(ROOT, "ref", "target", "release", "als-ref")


def run_one(ref, path):
    try:
        r = subprocess.run([ref, "run", path, "--json"], capture_output=True, text=True, timeout=180)
    except subprocess.TimeoutExpired:
        return {"abstain": {"class": "resource:wall-clock", "reason": "exceeded the gate's 180 s per-program budget"}}
    if r.returncode != 0:
        return {"error": f"als-ref exited {r.returncode}: {r.stderr.strip()[:200]}"}
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        return {"error": f"malformed protocol output: {r.stdout[:200]!r}"}


def read_ledger():
    if not os.path.exists(LEDGER):
        return None
    src = open(LEDGER, encoding="utf-8").read()
    m = re.search(r'^ceiling\s*=\s*(\d+)', src, re.M)
    ceiling = int(m.group(1)) if m else None
    classes = {}
    for cm in re.finditer(r'\[\[abstain\]\]\s*\nclass\s*=\s*"([^"]+)"\s*\ncount\s*=\s*(\d+)', src):
        classes[cm.group(1)] = int(cm.group(2))
    return ceiling, classes


def write_ledger(total, classes, evaluated, agree_note):
    lines = [
        "# REFERENCE-EVALUATOR ABSTAIN LEDGER (ADR-0015 decision 5) — what the judge's",
        "# evaluator does not evaluate yet, by class, over spec/wasm_cross + spec/programs.",
        "# Regenerated by `python3 scripts/check-ref-totality.py --write`; never edited.",
        "# An abstain is never a pass and never a fail. The total is SHRINK-ONLY:",
        "# scripts/check-ref-totality.py fails when the measured total exceeds `ceiling`",
        "# (coverage regressed) or falls below it without the ledger being ratcheted.",
        "#",
        "# Class vocabulary: parse · stdlib:<module.fn> · syntax:<form> · semantics:<rule>",
        "# · render:<Type> · runtime:<capability> · resource:<what> · semantics:type-mismatch",
        "# (a FINDING: the implementation accepted what the ALS-reading evaluator cannot type).",
        "",
        f"ceiling = {total}",
        f"evaluated = {evaluated}",
        "",
    ]
    for cls, n in sorted(classes.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append("[[abstain]]")
        lines.append(f'class = "{cls}"')
        lines.append(f"count = {n}")
        lines.append("")
    open(LEDGER, "w", encoding="utf-8").write("\n".join(lines))


def main():
    args = sys.argv[1:]
    ref_arg = args[args.index("--ref") + 1] if "--ref" in args else None
    write = "--write" in args
    ref = build(ref_arg)
    files = []
    for pat in CORPORA:
        files.extend(sorted(glob.glob(os.path.join(ROOT, pat))))
    if not files:
        print("::error::no corpus files found"); sys.exit(1)
    implemented = set(subprocess.run([ref, "stdlib-index"], capture_output=True, text=True).stdout.split())
    errs = []
    classes = collections.Counter()
    evaluated = 0
    called = collections.Counter()
    for path in files:
        rel = os.path.relpath(path, ROOT)
        src = open(path, encoding="utf-8").read()
        for m in CALL_RE.finditer(src):
            if m.group(1) in MODULES:
                called[f"{m.group(1)}.{m.group(2)}"] += 1
        out = run_one(ref, path)
        if "error" in out:
            errs.append(f"{rel}: evaluator FAULT (not an abstain, not a verdict) — {out['error']}")
        elif "abstain" in out:
            classes[out["abstain"]["class"]] += 1
        else:
            evaluated += 1
    # 2. every called stdlib fn is implemented or ledgered
    unknown = sorted(fn for fn in called if fn not in implemented and f"stdlib:{fn}" not in classes)
    # (a called fn that is never the FIRST abstain of any program is still unaccounted —
    # it is reached only behind another abstain; report it as a note, not a failure)
    for e in errs:
        print(f"::error::{e}")
    total = sum(classes.values())
    led = read_ledger()
    if write:
        write_ledger(total, classes, evaluated, "")
        print(f"ref-abstain ledger written: total {total}, {len(classes)} classes, {evaluated} evaluated")
    else:
        if led is None:
            errs.append("proofs/ref-abstain.toml is missing — run with --write")
        else:
            ceiling, lclasses = led
            if ceiling is None:
                errs.append("ledger has no `ceiling`")
            elif total > ceiling:
                errs.append(f"abstain total {total} EXCEEDS the ceiling {ceiling} — coverage regressed")
            elif total < ceiling:
                errs.append(f"abstain total {total} is BELOW the ceiling {ceiling} — ratchet: run --write and commit the ledger")
            if dict(classes) != lclasses:
                diff = sorted(set(classes) ^ set(lclasses))
                errs.append(f"ledger classes differ from the measurement (run --write): {diff[:8]}{'…' if len(diff) > 8 else ''}")
            for e in errs[len(errs) - 3:]:
                pass
    if unknown:
        print(f"note: {len(unknown)} called stdlib function(s) reached only behind another abstain (unaccounted for now): {unknown[:12]}{'…' if len(unknown) > 12 else ''}")
    for e in errs:
        if not e.startswith("::"):
            print(f"::error::{e}")
    if evaluated == 0:
        print("::error::zero programs evaluated — a broken instrument is not a pass"); sys.exit(1)
    if errs:
        print(f"ref-totality FAILED ({len(errs)} problem(s))"); sys.exit(1)
    print(f"ref-totality OK: {len(files)} programs, {evaluated} evaluated, {total} abstained in {len(classes)} classes (ceiling {total}), no evaluator fault, {len(implemented)} stdlib functions implemented.")


if __name__ == "__main__":
    main()
